#' Parameters of 2 virtual taxa.
#'
#' A dataframe with 2 rows and 16 columns with the parameters of two virtual taxa. It was generated by \code{\link{parametersDataframe}} and \code{\link{fixParametersTypes}}. It is meant to be used as input for \code{\link{simulatePopulation}}. It's columns are:
#'
#' \itemize{
#'   \item label: to store names (character string) of the virtual taxa.
#'   \item maximum.age: integer, maximum possible age of the individuals in years.
#'   \item reproductive.age: integer, age of sexual maturity in years.
#'   \item fecundity: integer, number of maximum viable seeds produced by a mature individual under fully suitable conditions.
#'   \item growth.rate: numeric, parameter of the logistic growth function.
#'   \item pollen.control: numeric in the interval [0, 1]. If 0, pollen productivity depends on environmental suitability only. The larger the number, biomass takes over environmental suitability in determining pollen productivity.
#'   \item maximum.biomass: integer, maximum biomass of the individuals.
#'   \item carrying.capacity: integer, maximum sum of biomass of the individuals. Very large carrying capacities plus a low maximum.biomass generates too many individuals for the simulation to remain efficient. Try to set carrying.capacity and maximum.biomass to carrying.capacity divided by biomass returns a number lower than 1000 (and even better if it is closer to 100).
#'   \item driver.A.weight: numeric in the interval [0, 1], represents the relative influence of the driver on environmental suitability.
#'   \item driver.B.weight: numeric in the interval [0, 1], represents the relative influence of the driver on environmental suitability. The sum of weights of drivers A and B should be 1.
#'   \item niche.A.mean: numeric, in the same units as driver A. It is the mean of the normal function defining the response of the virtual taxa to driver A.
#'   \item niche.A.sd: numeric, in the same units as driver A. It is the standard deviation of the normal function defining the response of the virtual taxa to driver A.
#'   \item niche.B.mean: as above, but for driver B.
#'   \item niche.B.sd: as above, but for driver B.
#'   \item autocorrelation.length.A: numeric, only useful if several drivers generated with different autocorrelation lengths are available (and identified by the column \code{autocorrelation.length}) in the \code{drivers} argument provided to the \code{\link{simulatePopulation}} function.
#'   \item autocorrelation.length.B: same as above.
#' }
#'
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name parameters
#' @usage data(drivers)
#' @format numeric vector of length 10000.
#' @seealso \code{\link{parametersCheck}}, \code{\link{parametersDataframe}}, \code{\link{simulatePopulation}}
"parameters"


#' List with two simulation outputs.
#'
#' A list of dataframes with two slots, output of \code{\link{simulatePopulation}}. Each slot corresponds to a virtual taxon from the \code{\link{parameters}} dataframe. Each dataframe has the following columns:
#'
#' \itemize{
#'   \item \emph{Time} integer, ages in years. Negative ages indicate the burn-in period.
#'   \item \emph{Pollen} numeric, pollen counts
#'   \item \emph{Population.mature} numeric, number of mature individuals.
#'   \item \emph{Population.immatre} numeric, number of immature individuals.
#'   \item \emph{Population.viable.seeds} numeric, number of viable seeds generated each year.
#'   \item \emph{Suitability} numeric, environmental suitability computed from the driver by the normal function/s defining the taxon niche.
#'   \item \emph{Biomass.total} numeric, overall biomass of the population.
#'   \item \emph{Biomass.mature} numeric, sum of biomass of mature individuals.
#'   \item \emph{Biomass.immature} numeric, sum of biomass of immature individuals.
#'   \item \emph{Mortality.mature} numeric, number of mature individuals dead each year.
#'   \item \emph{Mortality.immature} numeric, same as above for immature individuals.
#'   \item \emph{Driver.A} numeric, values of driver A.
#'   \item \emph{Driver.B} numeric, values of driver B, if available, and NA otherwise.
#'   \item \emph{Period} qualitative, with value "Burn-in" for burn-in period, and "Simulation" otherwise.
#' }
#'
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name simulation
#' @usage data(simulation)
#' @format numeric vector of length 10000.
#' @seealso \code{\link{simulatePopulation}}, \code{\link{plotSimulation}}
"simulation"


#' Lagged data generated by \code{\link{prepareLaggedData}}
#'
#' A dataframe resulting from the application of \code{\link{prepareLaggedData}} to the first slot of the list \code{\link{simulation}}. The order of the cases represent age. The first row contains the "older" sample, while the last row contains the "newest one". Therefore, for a lag equal to 1, any given case of the column \code{Response_0} is aligned with the data of the row above it. The dataframe columns are:
#'
#' \itemize{
#'   \item \emph{Response_0} numeric, values of the Response (simulated pollen abundance in this case) for the lag 0 (meaning that data in this column has not been lagged). This column is used as response variable by the function \code{\link{computeMemory}}.
#'   \item \emph{Response_1-100} numeric, time delayed values of the response for different lags (in years). Considered together these columns represent the endogenous ecological memory.
#'   \item \emph{Driver.A_0} numeric, values of the variable Driver A for the lag 0 (no lag). This column represents the concurrent effect of the driver over the response.
#'   \item \emph{Driver.A_1-100} numeric, time delayed values of Driver.A for different lags (in years). Considered together these columns represent the exogenous ecological memory.
#' }
#'
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name laggedSimData
#' @usage data(laggedSimData)
#' @format dataframe with 203 columns and 9900 rows.
#' @seealso \code{\link{simulatePopulation}}, \code{\link{plotSimulation}}
"laggedSimData"


#' Dataframe with pollen counts.
#'
#' A dataframe with the following columns:
#'
#' \itemize{
#'   \item \emph{age} in kiloyears before present (ky BP).
#'   \item \emph{pinus} pollen counts of Pinus.
#'   \item \emph{quercus} pollen counts of Quercus.
#'   \item \emph{poaceae} pollen counts of Poaceae.
#'   \item \emph{artemisia} pollen counts of Artemisia.
#' }
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name pollen
#' @usage data(pollen)
#' @format dataframe with 10 columns and 7986 rows.
"palaeodata"


#' Dataframe with palaeoclimatic data.
#'
#' A dataframe containing palaeoclimate data at 1 ky temporal resolution with the following columns:
#'
#' \itemize{
#'   \item \emph{age}  in kiloyears before present (ky BP).
#'   \item \emph{temperatureAverage} average annual temperature in Celsius degrees.
#'   \item \emph{rainfallAverage} average annual precipitation in milimetres per day (mm/day).
#'   \item \emph{temperatureWarmestMonth} average temperature of the warmest month, in Celsius degrees.
#'   \item \emph{temperatureColdestMonth} average temperature of the coldest month, in Celsius degrees.
#'   \item \emph{oxigenIsotope} delta O18, global ratio of stable isotopes in the sea floor, see \url{http://lorraine-lisiecki.com/stack.html} for further details.
#' }
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name climate
#' @usage data(climate)
#' @format dataframe with 10 columns and 7986 rows.
"climate"


#' Dataframe with sample pollen and climate data.
#'
#' A dataframe containing pollen and climate data interpolated at 0.1 ky temporal resolution with the following columns:
#'
#' \itemize{
#'   \item \emph{age} in years, at regular intervals of 100 years.
#'   \item \emph{pinus} interpolated pollen counts of Pinus.
#'   \item \emph{quercus} interpolated pollen counts of Quercus.
#'   \item \emph{poaceae} interpolated pollen counts of Poaceae.
#'   \item \emph{artemisia} interpolated pollen counts of Artemisia.
#'   \item \emph{temperatureAverage} average annual temperature in Celsius degrees.
#'   \item \emph{rainfallAverage} average annual precipitation in milimetres per day (mm/day).
#'   \item \emph{temperatureWarmestMonth} average temperature of the warmest month, in Celsius degrees.
#'   \item \emph{temperatureColdestMonth} average temperature of the coldest month, in Celsius degrees.
#'   \item \emph{oxigenIsotope} delta O18, global ratio of stable isotopes in the sea floor, see \url{http://lorraine-lisiecki.com/stack.html} for further details.
#' }
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name palaeodata
#' @usage data(palaeodata)
#' @format dataframe with 10 columns and 7986 rows.
"palaeodata"

#' @import ggplot2 viridis zoo stringr ranger HH
NULL
